### PR TITLE
Add storagepolicyname option to storageclass

### PR DESCRIPTION
**Pull request by Quantas**
Give the option to specify a `storagepolicyname` to be used for the default `StorageClass`

### CODE REVIEW

**Comment by stefanvangastel** [comment]
Thanks! lgtm

**Comment by Quantas** [comment]
Heh, so after looking again, it looks like I missed the changes to 'templates/storageclass.yaml'...

**Comment by stefanvangastel** [comment]
>_< Yeah.. I missed that too.. Are you going to send another PR or shall I insert it?

**Comment by Quantas** [comment]
I can send one in the morning :) Unless you were going to take care of it tonight. At least for me, it's 1AM.

**Comment by stefanvangastel** [comment]
Feel free, no rush :D

**Pull request merged**
